---
- name: Conditional block play
  hosts: all
  become: true

  tasks:
  - name: Install and configure Apache
    block:
      - name: Install the Apache package
        dnf:
          name: apache2
          state: installed
      - name: Install the templated configuration to a dummy location
        template:
          src: templates/src.j2
          dest: /tmp/my.conf
      - name: Start the apache2 service
        service:
          name: apache2
          state: started
          enabled: True
    when: ansible_facts['distribution'] == 'Fedora'


