---
- name: Install Apache
  hosts: frt01.example.com
  gather_facts: no
  become: yes

  tasks:
    - name: Install Apache package
      apt:
        name: apache2
        state: latest
    - name: Restart and enable the service
      service:
        name: apache2
        state: restarted
        enabled: yes
