---
- name: My first Ansible playbook
  hosts: all
  become: yes

  tasks:
  - name: Update the latest of an Apache Web Server
    apt: 
      name: apache2
      state: latest
    notify:
      - Restart an Apache Web Server

  handlers:
  - name: Restart an Apache Web Server
    service: 
      name: apache2
      state: restarted

