---
- name: Play 1 - configure the frontend servers
  hosts: frontends
  become: yes

  tasks:
  - name: Install  the Apache package
    apt:
      name: apache2
      state: latest
  - name: Start the Apache server
    service:
      name: apache2
      state: started

- name: Play 2 - configure the appliation servers
  hosts: apps
  become: true 

  tasks:
  - name: Install NTP
    apt:
      name: ntp
      state: latest
  - name: Start the NTP server
    service:
      name: ntp
      state: started
